### ISSUE TITLE
ui5-middleware-simpleproxy: x-csrf-token scenario

### ISSUE THREAD

**Issue by wmenge** [petermuessig/ui5-ecosystem-showcase#236]
The ui5-middleware-simpleproxy works like a charm for GET requests. However i have problems with PUT/POST requests to a C4C system which requires a valid csrf token.

From Postman my scenario works just fine: I can fetch and use a token for PUT/POST requests.

Also when I do not use the proxy and start Chrome without security, everything works fine out the of the box: ui5 libs fetch a token and uses it in the subsequent requests.

When using ui5-middleware-simpleproxy, the token is still requested and returned with the response, however: I get a 403 on any PUT/POST request with the following response header: 

x-csrf-token: Required

It seems that the token is generated by backend system is transparently returned, but somehow the backend server doesn't acknowledge the token.

Am I missing something?

regards,

Wilco Menge

**Comment by vobu** [comment]
this might be due to the original headers not being retained: https://github.com/petermuessig/ui5-ecosystem-showcase/blob/739db55dbe930408e84b8ddea5f974cf41c9c856/packages/ui5-middleware-simpleproxy/lib/proxy.js#L85
@petermuessig we might have to merge the current `req`'s header via https://github.com/villadora/express-http-proxy#userresheaderdecorator with the original ones

**Comment by wmenge** [comment]
Ok, I might take a stab at it. Is there any way to easily test this library?

**Comment by petermuessig** [comment]
@vobu: AFAIK the preserveHostHdr is just about the host header itself not about all other headers which are sent with the request. Maybe some headers are filtered - I need to verify this. Maybe there is a filter for the X-* headers. 

@wmenge : on the client-side (chrome) you see that the x-csrf-header is sent with the request? Or is the x-csrf-header lost as a result of the response of the GET request?

**Comment by petermuessig** [comment]
Here I found something:
https://stackoverflow.com/questions/21926062/csrf-token-not-working-in-nodejs-express

> Your issue is with Express not sending the CSRF token back in a header for POST/PUT/DELETE requests. Express's CSRF middleware is doing the correct thing in rejecting these requests when the header is missing.

**Comment by wmenge** [comment]
@petermuessig On the chrome side I actually see the header as I would expect it:
* On the first request, we pass "X-CSRF-Token: Fetch"
* In that response a token is returned
* In any subsequent request, that token is passed along with the request. However, the server responds with "x-csrf-token: Required"

If I leave out the proxy (by reducing the security settings of my browser), the token exchange works. So it seems like a cookie/session issue where the server might not recognize that this tokens belongs to my session.

**Comment by petermuessig** [comment]
Ahh, it could be the issue of secure cookies in an http context. This means we need to remove the secure flag in the cookie in the middleware when proxing https services. I will try to check asap - or if your want you can also look into this. I did a similar thing for the Java SimpleProxyServlet in OpenUI5: https://github.com/SAP/openui5/blob/master/src/testsuite-utils/src/main/java/com/sap/openui5/SimpleProxyServlet.java#L278-L292

**Comment by petermuessig** [comment]
@wmenge : I created a PR to test whether this fixes your issue. Can you validate the PR #241 for your scenario?

**Comment by petermuessig** [comment]
@wmenge: I released the 0.3.1 version of the simpleproxy middleware - you can try now - hopefully this fixes your issue.

**Comment by nair-sumesh** [comment]
hi @petermuessig , 
The issue is still being raised in BATCH request.
![image](https://user-images.githubusercontent.com/12034160/85464118-457f6780-b575-11ea-9812-0b3f690caad7.png)

![image](https://user-images.githubusercontent.com/12034160/85463524-bbcf9a00-b574-11ea-8861-b96855f64aac.png)
![image](https://user-images.githubusercontent.com/12034160/85464521-bd4d9200-b575-11ea-8327-1d1462c3620b.png)

However, I verified that the CRSF token is being passed in the batch request and its same as what was returned form previous call.

**Comment by petermuessig** [comment]
Thanks @nair-sumesh for verifying the fix. I need to see whether I can setup a similar testing scenario in the next days to verify this. At least the csrf-token is being retrieved and included for the $batch requests.

**Comment by lennart-m** [comment]
I just found out I have the same issue. First of all thanks a lot @petermuessig  for the new version 0.3.1, that fixed the first part of my problem.

It seems like the current version removes one semicolon to much.
In the debugger I got this:
![image](https://user-images.githubusercontent.com/20302675/86159405-9578a400-bb0a-11ea-87cb-600d383ae4ef.png)
I think the cookies should be replaced with `;` instead of empty string.
Otherwise the cookie value will be incorrect if the cookie value is followed by `Secure` and then there is something else.

But in my case there were other headers preventing chrome from applying the cookie: `Domain` and `Path`.
![image](https://user-images.githubusercontent.com/20302675/86160191-b1c91080-bb0b-11ea-90af-e5aa0f115de1.png)
In local testing domain is never equal to whatever is requested in the cookie and paths may differ as well due to being rewritten.

I might issue a pull request though I'm not at all confident with cookies and I have no idea if my changes are valid in other contexts as well. It works for me at least ;)
So it should be validated by somebody with experience in this domain.

**Comment by petermuessig** [comment]
Hi @lennart-m 

thanks for your feedback - you are right with the removal of the semicolon - I missed that piece. Will you create a PR or should I fix this directly?

THX, Peter

**Comment by lennart-m** [comment]
Hi @petermuessig 

I just made the changes locally in branch `fix-secure-cookie-proxy` where you made the change for version 0.3.1. When pushing it says I'm not allowed to push (HTTP 403). Is there anything I have to do? Maybe is the branch locked and I have to create another one? Or do I have to be unlocked?
I'm not that experienced working with Github.
Thanks in advance.

**Comment by vobu** [comment]
> I just made the changes locally in branch `fix-secure-cookie-proxy` where you made the change for version 0.3.1. When pushing it says I'm not allowed to push (HTTP 403). Is there anything I have to do? Maybe is the branch locked and I have to create another one? Or do I have to be unlocked?
> 
> I'm not that experienced working with Github.

you need to fork the entire repo in your own github account. then create a a branch and push there. subsequently you can use the branch in your fork to issue a PR into this repo. 
hth, v.

**Comment by lennart-m** [comment]
Thanks a lot @vobu 
I created #247 which fixes the part with missing semicolon.

What about removing other attributes `Domain` and `Path` as well?

**Comment by petermuessig** [comment]
Reading the documentation for `set-cookie` this makes also sense IMO:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

If we do not remove them, the browser will just not send the Cookies back.

Will you also add this to your PR?

Big thx,
Peter

**Comment by lennart-m** [comment]
I added a commit to the PR that removes attributes `Domain` and `Path` from cookies.

Though the "SameSite" may also have to be removed in the future as chrome warns me about this:
![image](https://user-images.githubusercontent.com/20302675/86415483-7bd08b80-bcc7-11ea-961f-9c1042079b0a.png)
Not sure if I should remove those or set another value there.

**Comment by petermuessig** [comment]
After reading the documentation about `SameSite` I think we can remove it as the default is `SameSite=Lax` or we set the cookie part to this value properly.

> Browsers are migrating to have cookies default to SameSite=Lax. If a cookie is needed to be sent cross-origin, opt out of the SameSite restriction using the None value. The None value requires the Secure attribute.

`SameSite=None` without `Secure` should be avoided. Will you also add this to the PR - that would be great! :-)

**Comment by lennart-m** [comment]
I added another commit, removing the SameSite attribute. I commented out a second version where the value of attribute `SameSite` is replaced with `Lax`, in case this will be necessary some time.

From my point of view it can be merged now.

**Comment by petermuessig** [comment]
A new version of the middleware proxy has been released: `ui5-middleware-simpleproxy@0.3.2`
